import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

live_config_reload = true

[window]
decorations = "Full"
dynamic_padding = false
option_as_alt = "OnlyLeft"
dynamic_title = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "ComicShannsMono Nerd Font Mono"
style = "Bold"

[font.normal]
family = "ComicShannsMono Nerd Font Mono"
style = "Regular"
